services:
  # Monolith: Full Stack Website (Spring Boot + React)
  - type: web
    name: issueflow
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: issueflow-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: issueflow-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: issueflow-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: issueflow-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: issueflow-db
          property: password
      - key: APP_JWTSECRET
        generateValue: true

databases:
  - name: issueflow-db
    plan: free
