spring.datasource.url=jdbc:postgresql://${dpg-d5t89kngi27c73f21td0-a:${5432}/${issueflow_db_0iqj}
spring.datasource.username=${issueflow_db_0iqj_user}
spring.datasource.password=${du3Jr0CCs5f6PKMyiLG7b8NswuPuPb8O}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${issueflow_jwt_secret_9F8xA1pL0QkR7TnM}
