spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER CONFIG (RENDER SAFE)
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE CONFIG (POSTGRES - RENDER)
# ===============================
spring.datasource.url=${postgresql://issueflow_db_user:GPQ2LW0qrkPg3IzXPUr4Rt8srPUk0gyU@dpg-d57pr99r0fns73dietn0-a/issueflow_db}
spring.datasource.username=${issueflow_db_user}
spring.datasource.password=${GPQ2LW0qrkPg3IzXPUr4Rt8srPUk0gyU}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Reduce startup time (IMPORTANT for Render Free)
spring.jpa.open-in-view=false
spring.main.lazy-initialization=true

# ===============================
# CONNECTION POOL (FAST STARTUP)
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

# ===============================
# LOGGING (CLEAN)
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
