spring.datasource.url=jdbc:postgresql://${dpg-d5ssdqfi8n1s73fr7ju0-a}:${5432}/${issueflow_db_7wu2B}
spring.datasource.username=${issueflow_db_7wu2E}
spring.datasource.password=${ZcElEXygENWYcCWPVQcmxSG0gnuGFEKm}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=${q61Nter5TUohdmhJWdJ4Y2mKr4elPWeeW9+8mqN8yiU}
